org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Fabric Properties
  # check these on https://fabricmc.net/develop
  minecraft_version=1.20.1
  yarn_mappings=1.20.1+build.10
  loader_version=0.16.14
  fabric_version=0.92.2+1.20.1

# Mod Properties
  group=ivorius
  mod_version=1.9.1
  displayname=Psychedelicraft
  authors=Ivorius, TripleHeadedSheep
  description=Adds drugs into Minecraft. Psychedelicraft specializes on realism and effects. Shaders are being utilized, so keep that in mind.

# Publishing
  modrinth_loader_type=fabric
  modrinth_project_id=8u2zZjRq

# Dependencies
  minecraft_version_range=1.20.1
  fabwork_version=1.2.0
  kirin_version=1.15.6+1.20.1
  modmenu_version=7.2.2
  terraformer_api_version=7.0.3

  use_sodium=1
  use_iris=1
  iris_version=1.7.6+1.20.1
  sodium_version=mc1.20.1-0.5.13-fabric

# TMI Testing
  tla_version=1.2.2-beta.5+1.20.1
  tmi_type=emi
  emi_version=1.1.22+1.20.1
  rei_version=12.1.785+fabric
	  rei_architectury_version=9.2.14
		rei_cloth_basic_math_version=0.6.1
		rei_cloth_config_version=11.1.136
